language: node_js
node_js:
  - "0.10"
cache:
  directories:
    - node_modules
    - bower_components
env:
  global:
    - secure: V1avJLT7GNb/b/0KkbCuZis1LiXYZBwhj91ywHfVhkje+dLHnDdG683TA/mmf1x5kWcxkjmfig98Wv+nCwThUv2x541IZQdKZKqc7XA39FkR0rbcyUzfUrEpxMjsISIYpGN8ZwDRGP0D1GZrnVklPysmEU8cPd9ZQvwXB8nGWbA=
    - secure: CasJs2kiY22LAZMika5GdmgdLlrz/QncLWWqplcZX5uGE6kTOeBfWJ26O+MBhHO8jxi+dTBkwzx/7aJrx0mKEsZMmeAAiiURTOsiG66OFjWNXYmpT1Kbao33l14IZJx8x3zzEEDqvLGJgYhVDRSiAwCYVQugvzTPR86mgip98pM=
addons:
  sauce_connect: true
before_install:
  - npm install -g npm@2
  - npm --version
  - npm install -g grunt-cli
  - grunt --version
before_script:
  - echo "Travis environment info ----"
  - hostname
  - which phantomjs
  - phantomjs --version
  - which chromedriver
  - chromedriver --version
  - grunt install
script: grunt full-test
