language: node_js
node_js:
  - "0.10"
cache:
  directories:
    - node_modules
    - bower_components
before_install:
  - npm install -g npm@2
  - npm --version
  - npm install -g grunt-cli
before_script:
  - phantomjs --version
  - grunt install
